server:
  port: 7000
#配置数据库驱动
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.12.131:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-coupon


  zipkin:
    #链路追踪可视化zipkin服务器
    base-url: http://192.168.12.128:9411/
    #关闭服务发现，否则spring cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    #设置使用http的方式传输数据
    sender:
      type: web
  sleuth:
    sampler:
      #设置抽样采集率为100%，默认0.1
      probability: 1

#mysql映射文件,自增组件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto