server:
  port: 25010
spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #端口
        port: 8791
        #控制台地址
        dashboard: localhost:8333
  redis:
    host: 192.168.12.128
    port: 6379

  zipkin:
    #链路追踪可视化zipkin服务器
    base-url: http://192.168.12.128:9411/
    #关闭服务发现，否则spring cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    #设置使用http的方式传输数据
    sender:
      type: web
  sleuth:
    sampler:
      #设置抽样采集率为100%，默认0.1
      probability: 1


  task:
    execution:
      pool:
        core-size: 8  #默认大小为8
        max-size: 50  #默认最大为int
  session:
    store-type: redis

  rabbitmq:
    host: 192.168.12.128
    port: 5672
    virtual-host: /
    #开发环境关闭缓存
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
