server:
  port: 9000
#配置数据库驱动
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.12.132:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order

#mysql映射文件,自增组件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto